function lista_de_libros(){

    const lista_de_libros = [

        {nombre:'El espejo Africano', valor: "$" + 500},
        {nombre:'Mi Planta de Naranja lima', valor:500},
        {nombre:'Edipo Rey', valor:500},
        {nombre:'El espejo Africano', valor: "$" + 500},
        {nombre:'Mi Planta de Naranja lima', valor:500},
        {nombre:'Edipo Rey', valor:500},
        {nombre:'El espejo Africano', valor: "$" + 500},
        {nombre:'Mi Planta de Naranja lima', valor:500},
        {nombre:'Edipo Rey', valor:500},
        {nombre:'El espejo Africano', valor: "$" + 500},
        {nombre:'Mi Planta de Naranja lima', valor:500},
        {nombre:'Edipo Rey', valor:500},
        {nombre:'El espejo Africano', valor: "$" + 500},
        {nombre:'Mi Planta de Naranja lima', valor:500},
        {nombre:'Edipo Rey', valor:500},
        {nombre:'El espejo Africano', valor: "$" + 500},
        {nombre:'Mi Planta de Naranja lima', valor:500},
        {nombre:'Edipo Rey', valor:500},
        {nombre:'El espejo Africano', valor: "$" + 500},
        {nombre:'Mi Planta de Naranja lima', valor:500},
        {nombre:'Edipo Rey', valor:500},
        {nombre:'El espejo Africano', valor: "$" + 500},
        {nombre:'Mi Planta de Naranja lima', valor:500},
        {nombre:'Edipo Rey', valor:500},
        {nombre:'El espejo Africano', valor: "$" + 500},
        {nombre:'Mi Planta de Naranja lima', valor:500},
        {nombre:'Edipo Rey', valor:500},
        {nombre:'El espejo Africano', valor: "$" + 500},
        {nombre:'Mi Planta de Naranja lima', valor:500},
        {nombre:'Edipo Rey', valor:500},
        {nombre:'El espejo Africano', valor: "$" + 500},
        {nombre:'Mi Planta de Naranja lima', valor:500},
        {nombre:'Edipo Rey', valor:500},
        {nombre:'El espejo Africano', valor: "$" + 500},
        {nombre:'Mi Planta de Naranja lima', valor:500},
        {nombre:'Edipo Rey', valor:500},
]
}